services:
  caijing18:
    build: .
    container_name: caijing18-app
    ports:
      - "5000:5000"
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    volumes:
      # 1. 仅挂载数据库文件或数据文件夹，不要覆盖整个 /app
      - ./data:/app/data 
    restart: unless-stopped
